# This workflow will build a .NET project.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0
      
    - name: Restore nuget packages
      run: nuget restore HL7SenderWinForm2015.sln
      working-directory: HL7SenderWinForm2015

    - name: MS Build
      run: msbuild HL7SenderWinForm2015.sln
      working-directory: HL7SenderWinForm2015
      

    - name: Upload Wix MSI Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: HL7-Installer
        path: HL7SenderWinForm2015/HL7_Setup/bin/x64/Debug/en-US
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: .\HL7SenderWinForm2015\HL7SenderWinForm2015
      
      
    
